services:
  database:
    image: 'postgres:16.9-bullseye'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '${DB_PORT}'
    volumes:
      - db/
  app:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
