services:
  database:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USER}'
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - database
    ports:
      - "80:8080"
    restart: unless-stopped

volumes:
  database_data: {}

