services:
  database:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=pgdb'
      - 'POSTGRES_PASSWORD=pgpass'
      - 'POSTGRES_USER=pguser'
    ports:
      - '5432:5432'
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  app:
    build: .
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  database_data: {}

