ALTER TABLE location ADD COLUMN country VARCHAR(255);
ALTER TABLE location ADD COLUMN county VARCHAR(255);
ALTER TABLE location ADD COLUMN city VARCHAR(255);
ALTER TABLE location ADD COLUMN road VARCHAR(255);
ALTER TABLE location ADD COLUMN house_number VARCHAR(255);