name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Connect via SSH
        run: |
           ssh -o StrictHostKeyChecking=no -p ${{ secrets.PI_SSH_PORT }} -i id_rsa ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
           echo "Removing repo folder if it exists;"
