name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Connect via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PI_SSH_PORT }} -i id_rsa ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
          set -e 
          
          echo "Removing repo folder if it exists"
          #TODO remove following line after development is done
          rm -rf ${{ github.event.repository.name }}
          git clone git@github.com:${{ github.repository }}.git
          cd ${{ github.event.repository.name }}
          
          echo "Decrypting secrets..."
          echo "${{ secrets.PI_DECRYPTION_PASS }}" > pass_file
          ./tools/bash/decryp0t_secrets.sh && echo "Secrets decryption done!"

          echo "Substituting secrets..."
          ./tools/bash/substitute_secrets.sh && echo "Secrets substitution done!"
          
          echo "Updating containers... "
          docker compose up -d
          
          echo "Removing codebase from host..."
          cd ..
          #rm -rf ${{ github.event.repository.name }} && echo "Codebase Removed"
          
          
          EOF