name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Connect via SSH and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.PI_SSH_PORT }} -i id_rsa ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} << 'EOF'
          set -e 
          
          echo "Removing repo folder if it exists"
          #TODO remove following line after development is done
          rm -rf ${{ github.event.repository.name }}
          git clone git@github.com:${{ github.repository }}.git
          cd ${{ github.event.repository.name }}
          
          echo "Decrypting secrets..."
          echo "${{ secrets.PI_DECRYPTION_PASS }}" > tools/enc_password_file
          if ! ./tools/bash/decrypt_secrets.sh; then
            echo "Secrets decryption FAILED!"
            exit 1
          fi
          echo "Secrets decryption DONE!"

          echo "Updating containers... "
          docker compose --profile prod down
          docker compose --profile prod up -d --build
          docker system prune -f
          
          echo "Removing codebase from host..."
          cd ..
          rm -rf ${{ github.event.repository.name }} && echo "Codebase Removed"
          
          EOF

      - name: Verify application health
        run: |
          echo "Verifying deployment health..."
          timeout=300
          while [ $timeout -gt 0 ]; do
            if curl -f https://${{ secrets.PI_HOST }}/actuator/health; then
              echo " Application is healthy!"
              break
            fi
            echo "Waiting for application to become healthy... ($timeout seconds remaining)"
            sleep 10
            timeout=$((timeout-10))
          done
          
          if [ $timeout -le 0 ]; then
            echo "Application failed to become healthy - deployment failed!"
            docker compose logs
            exit 1  
          fi

      - name: Remove SSH key
        if: always()
        run: rm -f id_rsa
